### ISSUE TITLE
编译报错Could not find jsc.kit.cameramask:camera-mask:0.3.0

### ISSUE THREAD

**Issue by mixml** [RapidAI/RapidOcrAndroidOnnx#11]
编译的时候提示:
Could not find jsc.kit.cameramask:camera-mask:0.3.0.
Required by:
    project :app

下载不了camera-mask-0.3.0.pom这个文件. 
能否提供一个camera-mask-0.3.0.pom的可用的下载地址

**Comment by benjaminwan** [comment]
https://github.com/JustinRoom/CameraMaskDemo

**Comment by mixml** [comment]
> https://github.com/JustinRoom/CameraMaskDemo

里面提供的下载地址也下载不了了的. 能发给我一份吗 malin888@vip.qq.com 谢谢

**Comment by benjaminwan** [comment]
有源码啊，可以直接集成。
JCenter里也有现成的包。
https://mvnrepository.com/artifact/jsc.kit.cameramask/camera-mask
如果都不行，就自己clone一个仓库，改一改提交到jitpack，也顺便造福所有人。

**Comment by benjaminwan** [comment]
https://jitpack.io/#JustinRoom/CameraMaskDemo/-SNAPSHOT
似乎可以直接用
repositories {
			mavenCentral()
			maven { url 'https://jitpack.io' } //添加这个源
}

dependencies {
	        implementation 'com.github.JustinRoom:CameraMaskDemo:-SNAPSHOT'
}

**Comment by mixml** [comment]
> https://jitpack.io/#JustinRoom/CameraMaskDemo/-SNAPSHOT 似乎可以直接用 repositories { mavenCentral() maven { url 'https://jitpack.io' } //添加这个源 }
> 
> dependencies { implementation 'com.github.JustinRoom:CameraMaskDemo:-SNAPSHOT' }

implementation 'jsc.kit.cameramask:camera-mask:0.3.0'
改成 implementation 'com.github.JustinRoom:CameraMaskDemo:-SNAPSHOT'
可以编译通过了, 谢谢!
